import pandas as pd
import streamlit as st

# chackbox function
def multiselect(title, unique_value):
    selected = st.sidebar.multiselect(title, unique_value)
    select_all = st.sidebar.checkbox('Select All', value=True, key=title)
    if select_all:
        selected_values = unique_value
    else:
        selected_values = selected
    return selected_values

# Dictionary for Creating Industry Column:
industry_dict = {
    "Frozen Momos": "Food & Beverages",
    "Renting e-bike for mobility in private spaces": "Transportation & Mobility",
    "Detachable Sleeves": "Apparel & Fashion",
    "Healthy Potato Chips": "Food & Beverages",
    "Brain Development Course": "Healthcare & Wellness",
    "Tourism": "Tourism & Hospitality",
    "Food Freshness Detector": "Technology & Innovation",
    "Disposable Urine Bag": "Healthcare & Wellness",
    "Energy Drink": "Food & Beverages",
    "Intelligent Skincare": "Technology & Innovation",
    "Pickle": "Food & Beverages",
    "Underwear": "Apparel & Fashion",
    "E-Bike": "Transportation & Mobility",
    "Restaurant serving 80 types of Maggi": "Tourism & Hospitality",
    "Belly Button Shaper": "Consumer Goods",
    "Ice-Pops": "Food & Beverages",
    "Menstrual Awareness Comic": "Healthcare & Wellness",
    "Pollution Resistant Fabric": "Apparel & Fashion",
    "Child Development App": "Healthcare & Wellness",
    "Gadgets for visually impaired people": "Technology & Innovation",
    "Kheer in variety of flavors": "Food & Beverages",
    "Kerala Banana Chips": "Food & Beverages",
    "Prickless Diabetes Testing Machine": "Healthcare & Wellness",
    "Smart Electric Motorcycle": "Technology & Innovation",
    "Smart Helmets": "Transportation & Mobility",
    "Wooden Toys": "Consumer Goods",
    "Healthy Oils": "Food & Beverages",
    "Male Intimate Hygiene": "Healthcare & Wellness",
    "Eggs": "Food & Beverages",
    "Student Community App": "EdTech & Learning",
    "Fiber Ice Cream": "Food & Beverages",
    "Wall Building": "Construction & Real Estate",
    "Customised Streetwear": "Apparel & Fashion",
    "Ayurvedic Products": "Healthcare & Wellness",
    "Indian Sweets": "Food & Beverages",
    "Metaverse App": "Technology & Innovation",
    "Braille Literary Device": "Technology & Innovation",
    "Eco-Friendly boxes": "Consumer Goods",
    "Yarn-Trading App": "Financial Services",
    "Home Dialysis Treatment": "Healthcare & Wellness",
    "Healthy Food Snacks": "Food & Beverages",
    "Digital Piggy Bank": "Financial Services",
    "Smart Audio Products": "Technology & Innovation",
    "Robotics and Automation Solutions": "Technology & Innovation",
    "Coconut based beverage franchise": "Food & Beverages",
    "Bamboo Products": "Consumer Goods",
    "Dog Hygiene": "Healthcare & Wellness",
    "Liquid Water Enhancer": "Food & Beverages",
    "Healthy Snacks": "Food & Beverages",
    "Sneaker Resale": "Retail & E-Commerce",
    "EdTech App": "EdTech & Learning",
    "Premium Surprise-Planning": "Gifts & Surprises",
    "Pothole Detection Software and Data": "Technology & Innovation",
    "Thin Crust Pizza": "Food & Beverages",
    "Hemp Food Products": "Agriculture & Sustainability",
    "Electric Auto Vehicle": "Transportation & Mobility",
    "Funeral Service": "Tourism & Hospitality",
    "Leather-free Shoes": "Apparel & Fashion",
    "Livestock health monitoring AI": "Agriculture & Sustainability",
    "Customised Keto Diets for various medical issues": "Retail & E-Commerce",
    "LPG Cylinder lock": "Technology & Innovation",
    "Delicacies": "Food & Beverages",
    "Comics & Animation": "Entertainment & Media",
    "Can Cocktails": "Food & Beverages",
    "Sugar-Free Icecream": "Food & Beverages",
    "Inventions": "Technology & Innovation",
    "Customised Apparels": "Apparel & Fashion",
    "Natural Hair Extensions": "Apparel & Fashion",
    "Toilet Spray with Essential Oils": "Consumer Goods",
    "Meads": "Food & Beverages",
    "Fresh Fruits": "Food & Beverages",
    "Ayurvedic Enriched Food": "Food & Beverages",
    "Streetwear": "Apparel & Fashion",
    "Motorcycle Luggage": "Transportation & Mobility",
    "Bags": "Consumer Goods",
    "Gifts": "Consumer Goods",
    "Agricultural Innovations": "Agriculture & Sustainability",
    "Homemade Foods": "Food & Beverages",
    "Dog Products": "Consumer Goods",
    "Portable ECG Device": "Healthcare & Wellness",
    "Roasted Peanut Products": "Food & Beverages",
    "Perfumes": "Consumer Goods",
    "Automatic Cradle": "Technology & Innovation",
    "Handicrafts": "Consumer Goods",
    "Coffee Products": "Food & Beverages",
    "Ventilated PPE Kits": "Healthcare & Wellness",
    "Automation Solutions": "Technology & Innovation",
    "Insurance Solutions": "Financial Services",
    "Organic Milk Products": "Agriculture & Sustainability",
    "Kunafa": "Food & Beverages",
    "Anti-Suicidal Fan Rod": "Healthcare & Wellness",
    "Jackfruit Products": "Food & Beverages",
    "Stainless Steel Items": "Consumer Goods",
    "Streaming Platform": "Entertainment & Media",
    "Portable Glass Attachment": "Technology & Innovation",
    "All-Kabaddi App": "Technology & Innovation",
    "Flowers": "Consumer Goods",
    "Scholarship Platform": "EdTech & Learning",
    "Handmade Reusable Scrap Materials": "Consumer Goods",
    "Vegetables Storage": "Agriculture & Sustainability",
    "Ayurvedic Wellness App": "Healthcare & Wellness",
    "Smart Locks": "Technology & Innovation",
    "Proposal Solutions": "Gifts & Surprises",
    "Technology layered Advertisement Services": "Technology & Innovation",
    "Rewards App": "Technology & Innovation",
    "Portable ophthalmic devices": "Technology & Innovation",
    "Insoles": "Apparel & Fashion",
    "Vegan Fermented Food": "Agriculture & Sustainability",
    "Sportswear": "Apparel & Fashion",
    "VR": "Technology & Innovation",
    "Bacon Jams": "Food & Beverages",
    "Reversible and convertible clothing": "Apparel & Fashion",
    "Plant-Based Protein": "Food & Beverages",
    "Fastest Cooking Device": "Technology & Innovation",
    "Lemonade": "Food & Beverages",
    "Washroom Finder": "Technology & Innovation",
    "Carenting for Elders": "Healthcare & Wellness"
}

# Sharks present and absent data:
present_sharks = ['Ashneer', 'Anupam', 'Aman', 'Namita', 'Vineeta', 'Peyush']
absent_sharks = ['Ashneer', 'Anupam', 'Aman', 'Namita', 'Vineeta', 'Peyush']